# Generated by Django 6.0.5 on 2026-05-25 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cv_file',
            field=models.FileField(upload_to='cv_files/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('INTERVIEW', 'Entretien Planifié'), ('ACCEPTED', 'Acceptée'), ('REJECTED', 'Refusée')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_published', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='skills_required',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='internshipoffer',
            name='technologies',
            field=models.JSONField(default=list),
        ),
    ]
