# Generated by Django 6.0.5 on 2026-05-28 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_application_ai_analysis_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_note', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='meeting_audio/')),
                ('ai_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_review', to='offers.application')),
            ],
        ),
    ]
